version: '3'

services:
  web:
    build: .
    depends_on:
      - 'db'
    ports:
      - '4000:4000'
    volumes:
      - '.:/app/'
  db:
    image: 'postgres:11'
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'

volumes:
  postgres: {}
  static:
    driver_opts:
      device: "tmpfs"
      type: "tmpfs"
